export default [{
  name: 'Rizzbot',
  model: '../assets/characters/rizzbot.fbx',
  isActive: true,
  price: 0,
  isLocked: false,
  danceAnimation: './assets/animations/rizzbot@dancing.fbx',
  runAnimation: '../assets/animations/rizzbot@running.fbx',
  slideAnimation: '../assets/animations/rizzbot@sliding.fbx',
  stumbleAnimation: '../assets/animations/rizzbot@stumbling.fbx',
  jumpAnimation: '../assets/animations/rizzbot@jumping.fbx',
},
{
  name: 'Grady Witch',
  model: '../assets/characters/witch.fbx',
  isActive: false,
  price: 200,
  isLocked: true,
  danceAnimation: '../assets/animations/witch@dancing.fbx',
  runAnimation: '../assets/animations/witch@running.fbx',
  slideAnimation: '../assets/animations/witch@sliding.fbx',
  stumbleAnimation: '../assets/animations/witch@stumbling.fbx',
  jumpAnimation: '../assets/animations/witch@jumping.fbx',
},
{
  name: 'Queen Candy',
  model: '../assets/characters/peasant-girl.fbx',
  isActive: false,
  price: 4000,
  isLocked: true,
  danceAnimation: '../assets/animations/peasant-girl@dancing.fbx',
  runAnimation: '../assets/animations/peasant-girl@running.fbx',
  slideAnimation: '../assets/animations/peasant-girl@sliding.fbx',
  stumbleAnimation: '../assets/animations/peasant-girl@stumbling.fbx',
  jumpAnimation: '../assets/animations/peasant-girl@jumping.fbx',
},
];
